/*
 Navicat Premium Data Transfer

 Source Server         : 书城
 Source Server Type    : MySQL
 Source Server Version : 80028
 Source Host           : localhost:3306
 Source Schema         : bookshop

 Target Server Type    : MySQL
 Target Server Version : 80028
 File Encoding         : 65001

 Date: 27/03/2022 11:26:47
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for goods
-- ----------------------------
DROP TABLE IF EXISTS `goods`;
CREATE TABLE `goods`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `cover` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `image1` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `image2` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `price` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `intro` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `stock` int NULL DEFAULT NULL,
  `type_id` int NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `fk_type_id_idx`(`type_id` ASC) USING BTREE,
  CONSTRAINT `fk_type_id` FOREIGN KEY (`type_id`) REFERENCES `type` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 120 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of goods
-- ----------------------------
INSERT INTO `goods` VALUES (9, 'You Fucking Got This : Motivational Swear Words Coloring Book', 'picture/1-1.jpg', 'picture/1-1.jpg', 'picture/1-1.jpg', '5.99', 'Relax Your Mind With This Beautiful Sweary Adult Coloring Book.\r\nBe Honest, You’ve had a Shitty Day', 10, 1, 'You would think that my picture was blurry, but it’s not. It looks like someone took random clipart and put some letters over it all in the same font. Unfortunately when they blew up whatever clip art they found it wasn\'t high enough resolution and everything is pixelated.', 'Purchased as a Christmas gift for my sister. She loved it and maybe even able to talk her spouse into colouring with the kids now.', 'Just as described and funny! I like that the back side of the pages are dark so the color bleed is t as noticeable. Great purchase, will buy again for gifts.', NULL);
INSERT INTO `goods` VALUES (10, ' I Am Confident, Brave & Beautiful: A Coloring Book for Girls', 'picture/1-2.jpg', 'picture/1-2.jpg', 'picture/1-2.jpg', '6.99', 'This groundbreaking coloring book is all about building a girl\'s confidence, \r\nimagination, and spirit! The 22+ coloring pages encourage girls to think beyond \r\nsocial conventions and inspire conversations with adults about what it really means to be confident, brave, and beautiful.', 10, 1, 'Wonderful book that came in at a perfect time. Each page has pictures and words to help boost self esteem and my 6 year old granddaughter who is being bullied \r\nin kinder has taken to this like a duck to water. Thank you for positive ways to help girls at all ages', 'I didn’t like that it came with a bend in it. Also, only 12 pages to color.', 'In a world of predictable coloring books for kids, this one really stands out. I bought one for my daughter and a handful of others for holiday gifts for her friends. What’s not to love about exposing \r\nIn a world of predictable coloring books for kids, this one really stands out. I bought one for my daughter and a handful of others for holiday gifts for her friends. What’s not to love about exposing the girls to ideas like “I am clever, bright, powerful, creative, inventive”, etc.', NULL);
INSERT INTO `goods` VALUES (11, 'Unbreakable: How I Turned My Depression and Anxiety into Motivation', 'picture/1-3.jpg', 'picture/1-3.jpg', 'picture/1-3.jpg', '14.99', 'In Unbreakable, Jay Glazer talks directly to you, his teammates, and shares his truth. All the  success \r\nfrom his screeching-and-swerving joy ride through professional football, the media, the MMA fighting \r\nworld, Hollywood, the military-warrior community, comes with a side of relentless depression and anxiety ', 10, 1, 'I purchased this book for my husband who has been struggling with all life is throwing at us lately - he is not much of a reader but has barely put this down.He has even requested I read about 10 pages of what he has read so far with the statement - someone finally put how I feel in words!! Though he isn’t finished yet and I am not even close I already recommend it as it is well written and so real!! ', 'Glazer wrote in the same \"voice\" one listens to every Sunday on Fox\'s NFL Sunday shows. I could almost hear his voice as I read. He is open & vulnerable writing, so his experiences might help anyone, whether it\'s short term or chronic. Also, the \"down to earth\" writing makes it a fast, easily comprehensible, read that sticks with you. No, not the typical self-help book... It\'s much better! Easily applicable to life.', 'I did not purchase the book, my kids bought for my husband, who suffers with depression. My husband told me that it might be an ok book but it is filed with the \"F\" Bomb. Good grief what is wrong with people to think people want to read vulgarity in a book about depression. ', NULL);
INSERT INTO `goods` VALUES (12, 'Eight Dates: Essential Conversations for a Lifetime of Love', 'picture/1-4.jpg', 'picture/1-4.jpg', 'picture/1-4.jpg', '21.95', 'Strengthen and deepen your love with a fun, ingenious program \r\nof eight life-changing conversations—on essential topics such as money, \r\n', 10, 1, 'There are several chapters missing in this book. It goes from page 88 to 122. See photo above. Will return it but want to make sure the new book is complete.', 'This is an awesome book and I can\'t more highly recommend it. Every couple can benefit from the conversations that this book helps create between you. This book also put words to some of the frustrations that each of us have had in trying to communicate together. Now, we have language and a method to discuss things without argument or tension. So helpful!', 'This is a good book whether you\'re on your first date or you\'re 1000th date. Most people don\'t talk about this stuff and it\'s so important to a lasting relationship. Get on it people.', 'This is an excellent book to help people avoid pitfalls of a bad relationship possibly. Fixing what may be wrong in a relationship. Getting to know ourselves, and what we may want and need in a relationship, prior to getting into one. And much more... ');
INSERT INTO `goods` VALUES (13, 'A Million Kawaii Cuties: The Sweetest Things to Color (A Million Creatures to Color)', 'picture/1-5.jpg', 'picture/1-5.jpg', 'picture/1-5.jpg', '8.99', 'Explore the enticing world of kawaii in this beautiful coloring book!', 10, 1, 'Such an adorable book. The cover alone is beautiful. Bought one for me and one for my friend and she loved it. This artist\'s last two books, are the best ones in her collection. Super adorable and fun to color.', 'There are many humorous, fun coloring pages in this book. It’s cute on steroids! The illustrations are appealing for both kids and adults. You will see things made Kawaii cute that you wouldn’t even think of. If you liked her previous coloring books, you will love this one.', 'This book is yet another fantastic offering from Lulu Mayo. The artwork is adorable and the pictures make me smile. The paper is great and her work seems to get better and better with each book. I would highly recommend this book.', 'This was a beautiful little book and such fun characters');
INSERT INTO `goods` VALUES (14, '100 Left Hand Patterns Every Piano Player Should Know: Play the Same Song \r\n', 'picture/1-6.jpg', 'picture/1-6.jpg', 'picture/1-6.jpg', '17.98', '00 Left Hand Patterns Every Piano Player Should Know (Play the Same Song 100 Different Ways) \r\nby Music Mentor Jerald Simon, is one of the books from the Music Motivation® Series. This book \r\nwas created to help piano students of all ages and skill levels learn how to improvise and arrange music of their own.', 10, 1, 'This product is sort of a bridge for people who grew up rigidly learning Bach and Mozart piano pieces who now want to learn how to be more imaginative, loose, contemporary .... but are trapped in etude drill brain', 'Don\'t get deceived by the cover like me. It\'s not a book on left hand patterns, just the first pages are. Most of the book is a fake book. I would have understood if the fake book had annotations and tips, but no.', 'This is an excellent book and its unlike any that I have seen. Its great practice to work through the book trying each left hand pattern. I make note of the ones I like so I can quickly go back to work on them more. It had some good', 'This book is in many ways totally useless. The format and content do not provide any meaningful information on left hand playing with a fake book. \r\nThis book is in many ways totally useless. The format and content do not provide any meaningful information on left hand playing with a fake book.');
INSERT INTO `goods` VALUES (15, 'Music Theory for the Bass Player: A Comprehensive and Hands-on Guide', 'picture/1-7.jpg', 'picture/1-7.jpg', 'picture/1-7.jpg', '31.46', 'Music Theory for the Bass Player is a comprehensive and immediately applicable \r\nguide to making you a well-grounded groover, informed bandmate and all-around \r\nmore creative musician.', 10, 1, 'How this book gets five star reviews is beyond me. I\'m a reasonably good bass player and wanted to increase my theory knowledge. Well, there is nothing at all in this book that most half decent bass players won\'t already know. Perhaps it\'s aimed at people who just play by ear and want to understand what they are doing.', 'I have read many syllabi, lesson plans and observed many lessons and this book has the unmistakable quality of a teacher who is passionate about their subject and has an instinctive understanding of the way we all earn, it is a rare gift.', 'I first started playing Bass over 30 years ago and have had numerous lessons and bought a truckload of books, instructional videos over the years. After a long lay off I returned and found Ari\'s book on Amazon and it is simply the best book / advice I have ever received.', 'This is the book of an excellent online course. It is extremely carefully thought out and well organised and basically does exactly what it says on the tin. Over 20 lectures, each one requiring a minimum of about 100 minutes to complete, it introduces the bass player to key musical concepts in a digestible form and provides a wealth of exercises which are excellent at breaking down left and right hand techniques and isolating and removing bad habits while promoting good ones.');
INSERT INTO `goods` VALUES (16, 'Little Book of Louis Vuitton: The Story of the Iconic Fashion House', 'picture/1-8.jpg', 'picture/1-8.jpg', 'picture/1-8.jpg', '12.61', 'Little Book of Louis Vuitton is the pocket-sized and fully illustrated story of one of the world\'s most \r\nluxurious fashion houses.', 10, 1, 'A couple of things here...I don’t know what’s going on with these price spikes but a book that was worth $80 jumped to $180 in a week. That’s absurd especially considering the other Catwalk books are in the $50-$60 range. Second, my book arrived with stains on the fêting cover. Not impressed, it’s going back. ', ' I honestly didn\'t pay attention to the measurements of the book so I was surprised at how big & heavy it is! Nonetheless, I really love it, the colour is perfect. The only concern I have is that the cover is a kind of fabric so I got to be careful for it not to stain. Overall I\'m a happy customer.', 'So cute and such a good coffee book and a lot bigger then what I thought but I’m not complaining the more the better', 'Highly recommend this to fashion-centric individuals. Great pictures depicting the fashion of LV. ');
INSERT INTO `goods` VALUES (18, 'The Botanist\'s Sticker Anthology INSTALL AND MAINTAIN GRID TIED', 'picture/1-9.jpg', 'picture/1-9.jpg', 'picture/1-9.jpg', '13.99', 'Get lost in the beauty of the natural world in this captivating collection of botanical stickers.\r\n\r\nPage after page is packed with beautiful vintage drawings of ornamental flowers, tropical ferns, \r\nand other exotic plants and fungi.', 10, 1, 'Oh my word, this is the most beautiful thing you can imagine! The previous reviewer who said to buy two of these books(1 for use; 1 to savor), was absolutely right! I can barely bring myself to disturb this gorgeous thing. But I will. With complete glee. Every once in a rare blue moon you get more than you bargained for. This was that rare delicious moment. I luv it so much. Good job!! =) ', 'This book is absolutely, completely beautiful. I ordered a second because one of them I am adding to my permanent book collection- I couldn\'t bear to use it. If you are into journaling, art journaling, mixed media, planning, etc and are also into flora and plants, you have to have this book in your collection. Get two- one to use and one to keep.', 'I am using these fabulous stickers to embellish handmade greeting cards. ', 'This has literally just landed on my doorstep. I just had to leave a review.. this is a totally stunning book.. if you have a use for some stickers of this nature.. buy it!');
INSERT INTO `goods` VALUES (19, 'Hayao Miyazaki The BRAND NEW winter release from Jessica Redland', 'picture/1-10.jpg', 'picture/1-10.jpg', 'picture/1-10.jpg', '37.49', 'A richly illustrated journey through the extraordinary cinematic worlds of beloved \r\nfilmmaker Hayao Miyazaki \r\n\r\nFor over four decades, Hayao Miyazaki has been enchanting audiences of all ages. \r\nHis animated films, often featuring children navigating unfamiliar and challenging worlds, \r\noffer timeless explorations of youth and what it means to grow up', 10, 1, 'Truly a must own - it\'s a beautiful book!!! Buy it trust me!! ', 'This is a lovely and comprehensive volume on the works of Miyazaki. It is a delight.', 'I was not able to afford this at the time I visited the exhibit. It’s a fantastic representation of Hayao Mizaki’s work and the exhibition at the Academy Museum. A must for Miyazaki fans! I’m grateful to own this.', 'I was not able to afford this at the time I visited the exhibit. It’s a fantastic representation of Hayao Mizaki’s work and the exhibition at the Academy Museum. A must for Miyazaki fans! I’m grateful to own this. ');
INSERT INTO `goods` VALUES (20, 'Avatar: The Last Airbender--The Lost Adventures and Team Avatar Tales Library ', 'picture/1-11.jpg', 'picture/1-11.jpg', 'picture/1-11.jpg', '23.99', 'The comics continuation of Nickelodeon\'s hit series Avatar: The Last Airbender returns with \r\na treasure trove of short stories, collected for the first time in hardcover!', 10, 1, 'I love all the library edition books but my only complain (like another review I saw) is how the cheaply the spine of the book was made. It makes an option crinkle noise when u open and move it. otherwise I love the cover art and the stories inside. it was still a must have last edition to my collection ', 'I teach 6th grade English. We do 10 minutes of reading at the beginning of class each day. Of course, I have a handful of non-readers who will do anything not to read. All these same students fight over this book every day.', 'There are several reviews that mention how the difference in size between this and the previous omnibus books is unacceptable. For a collector, that might be understandable. But if you\'re a fan like I am, the size is unimportant. It has beautiful artwork and is a great chance to enjoy more of the series you and I love. Go for it. ', 'After reading reviews I was a bit worried I would receive a damaged book. However, the book arrived well packaged and shrink wrapped with no damage on any of the covers. Overall it looks great and I paid less than I would have getting it from a big book store. ');
INSERT INTO `goods` VALUES (21, 'Disney Dreams Collection by Thomas Kinkade Studios: 2022 Wall Calendar', 'picture/1-12.jpg', 'picture/1-12.jpg', 'picture/1-12.jpg', '12.99', 'This tenth edition of the Disney Dreams Wall Calendar captures the timeless \r\nmagic of classic Disney stories and their captivating characters in settings imagined \r\nby Thomas Kinkade Studios.', 10, 1, 'I buy a Thomas Kinkade Disney Calendar every year. I hang it on my Refrigerator door and enjoy the pictures month after month, year after year. I also save each one from year to year. ', 'This is a very detailed beautiful Disney calander! I love all the pictures!! ', 'I\'ve gotten Thomas Kindade\'s Disney Calenders before. Some of his pictures can be a little dark and in shadow. I\'m especially pleased with the selection they chose of his work this time. Most of the pics are some of his brighter ones he did for Disney. ', 'I should have paid more attention when ordering- I don’t like that the numbers for each day are written in the bottom middle of the square instead of traditional placement (top left corner). Oh well. The pictures look nice. ');
INSERT INTO `goods` VALUES (22, 'Humans New Stories About Mythic Heroes Divorce And Separation', 'picture/1-13.jpg', 'picture/1-13.jpg', 'picture/1-13.jpg', '14.90', '\"Just when we need it, Humans reminds us what it means to be human . . . \r\none of the most influential art projects of the decade.” ―Washington Post ', 10, 1, 'Ignore the reviews of it coming dirty. The material they used for the cover is susceptible to finger prints; grab a Clorox wipe and wipe them off. The book is 437 pages, a lot more than I expected and after reading a few pages was worth every penny. I highly recommend this book.', 'It is an exceptional reminder of who humans are, and how we are more similar than different. It\'s like people watching, but from the comfort of your home. These stories bring out a level of empathy in a reader that can only be extracted through the brave vulnerability of the subjects.', 'Like the previous commenter I to pre-ordered and was excited to give as a gift. The book came with fingerprints all over it and it only got more as I picked it up. Even though my hands were clean they left permanent marks all over it.I guess \'humans\' are messy and I\'ll just have to get over it. ', 'The book is amazing, and that is why I\'m giving it 4 stars, but if you haven\'t done it already, don\'t buy it from Amazon. The cover is dirty and slightly damaged. ');
INSERT INTO `goods` VALUES (24, 'Patterns of India: A Journey Through Colors, Textiles and type', 'picture/1-14.jpg', 'picture/1-14.jpg', 'picture/1-14.jpg', '4.99', 'It\'s the trip of a lifetime—a textile-based tour of colorful Rajasthan, India featuring more \r\nthan 200 lush photographs depicting everyday life in one of the most vibrant regions in the world.', 10, 1, 'This is a beautiful book, cover to cover. Since I can’t go to India to see theses beautiful places and people, this is the next best thing! Combine this book with watching Hindi/India movies via Amazon or Netflix and you have a mini vacation right in your living room. Safest way to travel at this time.Namaste', 'A stunning visual feast for the eyes. Explore the beauty of India through Christine Chitnis lens. Textures, colors and culture all presented fabulously. Escape on an visual adventure that will not disappoint. A wonderful coffee table book.', 'This is a beautiful book, brimming with vivid colours, intricate patterns, and keen attention to detail. I have been enjoying it bit by bit since it first arrived, I know I will be returning to these images again and again for inspiration. ', 'Photos are interesting but the pages are dull, not vibrant pictures at all. The photography itself is interesting but I was expectIng slick sharp pictures and this was not that. Still was worth having. ');
INSERT INTO `goods` VALUES (25, 'Ernst Haas: New York in Color, 1952-1962 winter release', 'picture/1-15.jpg', 'picture/1-15.jpg', 'picture/1-15.jpg', '27.99', 'The first book on master photographer Ernst Haas\'s work dedicated to both his classic \r\nand newly discovered New York City color photographs of the 1950s and 60s.', 10, 1, 'Like everything about this book. The color photographs are very inspiring even though they were from 60-70 years ago, Haas was a genius in taking pictures in the city and using motion in his shots. His skill with film and his trusty camera that long ago was unmatched! ', 'Shows why Haas is a true master and innovator--wonderful! ', 'This book is fantastic from start to finish. Excellent use of color throughout. A bargain for the price. ', NULL);
INSERT INTO `goods` VALUES (26, 'Made for Living: Collected Interiors for All Sorts of Styles', 'picture/1-16.jpg', 'picture/1-16.jpg', 'picture/1-16.jpg', '12.99', 'NATIONAL BESTSELLER • The trendsetting designer known for her effortless style \r\nshares the secrets of the art of layering, with more than 250 gorgeous photographs of her \r\nsignature interiors.  ', 10, 1, 'Very nice design and decor book . Just what I needed for my coffee table and because I’m a designer myself I actually look through my books and this one is great ! I love the mixing of subtle textures and modern rustic feels.', 'This is a beautiful book, stuffed full of lovely photographs. The author\'s design style is clearly lovely and there is some useful information in here, though mainly illustrated by huge, expensive houses. 4 rather than 5* for me because I found the author\'s writing style fairly self-absorbed and irritating I\'m afraid. ', 'I am a huge Amber fan and love the detail in this book. Full of secrets and hidden gems for all budgets! Highly recommend! ', 'The book is full of beautiful photos. I don\'t follow Amber Lewis on social media so I found it inspiring for ideas on how to put together a neutral palette without being boring. However, this book is not an instructional or helpful to non-designers as it claims to be.');
INSERT INTO `goods` VALUES (27, 'This is Home: The Art of Simple Living release from Jessica Redland', 'picture/1-17.jpg', 'picture/1-17.jpg', 'picture/1-17.jpg', '25.09', 'This is Home is a back-to-basics guide on how to create authentic wholehearted interiors. \r\nIt\'s about living simply – finding the essence of what makes you happy at home and creating spaces that reflect your needs and style. ', 10, 1, 'interior books are everywhere and not always that inspiring. some are decorating by numbers, telling us how to pick paint, what types of furniture to use etc etc. Usually they are by interior designers trying to sell their \'look\' .', 'I have an addiction for books on interior design that are soulful and get to the heart of simplicity and beauty. This book is a wonderful experience - just to sit and look through. I have it by my couch, so I can look at it often and feel inspired by the images. ', 'nice thick book for use in stacking with other books to decorate built in/book shelving.', 'Lovely book with tons of small inspirations- things you can actually make/realize yourself. I don’t read books like this (just too cliche) but pictures shows a lot of great details. ');
INSERT INTO `goods` VALUES (28, 'Snowflakes Over The Starfish Café: The BRAND NEW winter ', 'picture/1-18.jpg', 'picture/1-18.jpg', 'picture/1-18.jpg', '3.99', '\'Heartbreakingly moving and yet beautifully uplifting, I cried for all the right reasons!\' Jo Bartlett', 10, 1, 'Great book, couldn’t put it down! Each character so real, so emotional! I had tears, smiles and hope! Of course I loved the setting! The details are rich and poignant. Well researched and written.', 'I love so much about this story, The characters were brilliant in every event needed. You laughed , cried , and might of wanted to slap some sense into a few characters for their pain they caused but it just made the lead characters stronger', 'Credible characters who are flawed and therefore relatable. The author provided a balanced representation of how us humans are affected by difficult life happenings and how we can overcome them when time has passed and we can assess where we are and where we want to be. Less a Holiday story than a coming of age one. Enjoyable. ', 'Redland always has character of all ages that seem like friends as you are reading her books. There is heartache in this story but it is set against love and hope. An excellent way for those who love to read to escape, especially now.');
INSERT INTO `goods` VALUES (29, 'A Collection of Stories for 2 Year Olds most beloved fairytale characters', 'picture/2-1.jpg', 'picture/2-1.jpg', 'picture/2-1.jpg', '9.99', 'Snuggle up to your favorite nursery rhymes and drift into the magical worlds of \r\nall your most beloved fairytale characters with this unique collection of enchanting \r\nstories carefully selected to enthrall 2-year-olds.', 10, 2, 'It\'s a nice book but only 3 stories... the rest of the book Full with babies songs, it doesn\'t even show the full songs, only the first line/paragraph of each song.', 'Three Little pigs and a random story about a boy and his dog. The rest of the book are one page or 2 page nursery rhymes. Although the illustrations are very pretty it leaves a lot to be desired. It should be called \"A Collection of Nursery Rhymes and 3 stories\" to be more accurate and honest.', 'This book is all over the place. Different illustration styles (most I don\'t love), and only a few long stories, with the rest just being short nursery rhymes. It\'s proven difficult to find good books for this age range.', 'Lovely book, very nice presented and great as a gift but I was expecting more stories than nursery rhymes. The idea being a book for bedtime and not singing.');
INSERT INTO `goods` VALUES (30, 'Five-minute Stories: Over 50 Tales and Fables, and well-loved fairy tales. ', 'picture/2-2.jpg', 'picture/2-2.jpg', 'picture/2-2.jpg', '8.50', 'There is always time to read together with this deluxe treasure-trove of five-minute stories, \r\nfables, and well-loved fairy tales. ', 10, 2, 'The stories are written more for adults than for young children in mind. Many phrases and words used are more appropriate for older children (6+) and adults-- may be too complex for younger kids.', 'Awesome content and beautiful illustrations! I love sharing stories from my very early childhood with my kids. So many classics that contain a moral and helped shaped my young imagination. Each story is short enough to conveniently read at bedtime with no problem!', 'While I don\'t agree with some of the versions of the stories, the length of them and the pictures more than make up for it. It works exceptionally well for story time before bed.', 'Lovely book... But wish the seller would use actual photos of the books contents.Doesn\'t have humpty dumpty in it at all (false advertising) but it\'s a nice book.. ');
INSERT INTO `goods` VALUES (31, 'James Herriot\'s Treasury for Children: Warm and Joyful Tales by the Author', 'picture/2-3.jpg', 'picture/2-3.jpg', 'picture/2-3.jpg', '19.79', 'James Herriot\'s award-winning stories for young readers bring the farmyard world \r\nof Herriot\'s Yorkshire to vibrant life. ', 10, 2, 'Sweet book to read to your kids. The pictures are gorgeous! The stories are written as if addressed to adults (no talking down to the audience), but the subject matter keeps the kids excited about the story. Quality literature.', 'This book was a treasure from the moment we set eyes on it on Christmas morning. It is so beautiful, high quality, generous and beautifully illustrated and written. It is a thing of beauty and my children were so enraptured by the lovely, gentle, joyful tales that my 4 year old girl and 7 year old boy begged for it every night at bedtime.', 'I absolutely love this cd and my children enjoyed listening to the stories travelling in the car ', 'What I disliked was I looked at this for a gift for my grandchild age 6. I thought after reading the reviews it was a cd and book. Very misleading. I hope my granddaughter enjoys it.');
INSERT INTO `goods` VALUES (32, 'Winnie the Pooh My First Bedtime Storybook Tigger, Rabbit, and more', 'picture/2-4.jpg', 'picture/2-4.jpg', 'picture/2-4.jpg', '7.99', 'Adventure in the Hundred-Acre Woods!\r\nJoin favorite friends from the Hundred-Acre Woods Pooh, Piglet, Tigger, Rabbit, and more, \r\nfeaturing six bedtime stories in one very special storybook. ', 10, 2, 'Many of original Pooh stories are lengthy. My 3 yr old grandchildren become bored quickly. But these stories are prefect. Pictures on every page. Shorter stories so my grandchildren remain engaged. Would buy again or as a gift. Hard bound with beautiful cover', 'Bought this book for my newborn son. I read to him every night, stories are perfect length. The quality of the pages and pictures are amazing! I love all things Disney.', 'A very cute book for little ones. The stories are pretty short though and I could easily read 2-3 for one bedtime. But still a good book! ', 'I bought it for my granddaughter. She will be born around Dec. 15th 2021. This book took about a month longer to get here but worth the wait. ');
INSERT INTO `goods` VALUES (33, 'The Cursed Carnival and Other Calamities: New Stories ', 'picture/2-5.jpg', 'picture/2-5.jpg', 'picture/2-5.jpg', '9.99', 'Best-selling author Rick Riordan presents ten new stories--including one of his own--\r\nabout beloved heroes that sprang from the imaginations of some of the best middle \r\ngrade authors working today.', 10, 2, 'I got this for my son who is a huge Rick Riordan fan. According to him, you have to read the other Rick Riordan presents books in order to understand this one. ', 'My son likes Percy Jackson books and loved this one, read it in a few days. Wish it lasted longer..lol.. ', 'I have followed Rick Reardon since the Jackson series. This book is a big disappointment compared to his previous stuff. It is more like delusional tripe.', 'Pleased with the transaction, gift for grandson, he was surprised! :) ');
INSERT INTO `goods` VALUES (34, 'We Will Always Love You:\r\nA Children’s Story Explaining Divorce', 'picture/2-6.jpg', 'picture/2-6.jpg', 'picture/2-6.jpg', '9.98', 'n times of change and family upheaval, children are often the ones in need of the \r\nmost validation and support, as they often blame themselves for the separation\r\n\r\nWe Will Always Love You helps to gently explain to children the changes and challenges \r\nthey may face during this difficult time, all while reinforcing the love that both parents have for them', 10, 2, 'My wife and I are unfortunately going through a divorce and we are currently splitting custody of our 2 kids. One is 6 and one is 4. I was looking for an easy, direct, kid friendly book for their age group along with one for adults to help prepare my children for the feelings that I believe will come from our divorce… whether right away or to help soften and prevent any childhood traumas that may occur because of the divorce years down the line.', 'Over half of the book shows the boy being happy while with *both* parents. The first 12 pages talk about how fabulous it was when they were together. When dad leaves, the boy says it \"broke my heart.\" And then, \"I had to hold it all in and pretend to be tough.\" Worst advice possible!', 'Amethyst wrote a scathing review. I would like to point out to this person, that young boys sometimes try to hold things in, and we should acknowledge that. Nothing wrong with that. It\'s not a novel, so it tries to present its story in a short format', NULL);
INSERT INTO `goods` VALUES (35, 'The Little Bookroom and In the home of my childhood filled with poetry', 'picture/2-7.jpg', 'picture/2-7.jpg', 'picture/2-7.jpg', '3.02', '“In the home of my childhood there was a room we called ‘The Little Bookroom.’ . . . That dusty bookroom, \r\nwhose windows were never opened . . . opened magic casements for me through which I looked out on other worlds . . . \r\nworlds filled with poetry and prose and fact and fantasy. . .” —Eleanor Farjeon', 10, 2, 'I\'ve had this book for over 60 years, and I still adore it. Whenever the world is \"too much with me,\" I pull it out and read a couple stories. Recently I bought a copy for a British friend who was having some stressful times, and she too found it soothing and fascinating. ', 'i loved this as a child and love it even more now! The stories will stay with you forever. Truly a masterpiece.', 'I bought it as a bedtime story book. Unfortunately it is impossible to read and finish the stories.', 'Have been looking ofr one of the stories in this for ages. Thanks.');
INSERT INTO `goods` VALUES (36, 'It\'s Not Easy Being a Bunny and It’s Better Being a Bunny,available now!', 'picture/2-8.jpg', 'picture/2-8.jpg', 'picture/2-8.jpg', '1.64', 'P.J. Funnybunny doesn\'t want to be a bunny anymore! In this hilarious Beginner\r\nBook, a young bunny explores life with different animal friends. And don’t miss the charming follow-up, \r\nIt’s Better Being a Bunny, available now! This is a perfect gift for Easter or celebrating bunnies all year round.', 10, 2, 'Book is just as it should be. Pages are centered correct. Pictures are vibrant. Words are perfectly sized. Can’t wait to read my daughter this book on Easter.', 'Book was sent bound upside down and backwards. I would refund it but amazons new return situation is such a hassle it doesn’t make it worth it for $6. If you want to buy it in the store and know you’re getting the book correct I would 100% do that!It’s an adorable story that I remember loving when I was a kid.', 'I had this book as a kid and loved it. So I was excited to get it again for our daughter. It was an Easter gift and a big hit. She thinks it hilarious that a bunny tries to live with all these different animals. She will shout the animal out as we turn the page.', 'I loved this book as a child, so I decided to get it for our 3 year old. She loves it! She loves animals so she enjoys yelling out the animal names. We\'ve had it for a couple of weeks now and she has requested it for story time every night.');
INSERT INTO `goods` VALUES (37, 'Not a Cat: a memoir 2nd Edition in Silicon Valley Paperback ', 'picture/2-9.jpg', 'picture/2-9.jpg', 'picture/2-9.jpg', '17.48', 'A funny, expansive, affirming story with a powerful message of self-determination \r\nfor young kids: No one can label us if we do not allow ourselves to be labeled. \r\nOur identities are ours to choose and to live.', 10, 2, 'My 6 year old loves this book. It\'s a favorite in our household. After every reading we explore what it means to be uniquely you. Regardless of the boxes we think we should check. We are limitless! ', 'This immediately became my daughter’s favorite book. It’s silly and sweet, and the message resonated. I have heard her tell her older brother ‘No one know me better than me!’ and it makes my heart swell! This is one I don’t mind reading again and again.', 'I corresponded regularly with Gato when he roamed the earth...and it mattered not if he was a cat or another kind of being: he was charming, learned, curious, loyal, and only mildly fractious. Give your child (or your grown self)a chance to know him through this sheer delight of a memoir. ', 'I loved this book; it was mischievous, inspiring and fun - I am excited to gift it to children and cat lovers. It is beautifully illustrated - and dictated by a real life cat ;) I look forward to more books by this writer! ');
INSERT INTO `goods` VALUES (38, 'A Song Called Home And Applied Approach 1st ed and so on', 'picture/2-10.jpg', 'picture/2-10.jpg', 'picture/2-10.jpg', '15.29', 'From award-winning author Sara Zarr comes a story of the small moments that show us \r\nwho we are, and how family is not just something you’re part of, but something you make.', 10, 2, 'Thanks to NetGalley & HarperCollins Children’s Books for a digital advance reader\'s copy. All comments and opinions are my own.', 'Lou and Casey’s mom is remarrying, and the girls aren’t happy, It’s going to mean a new “we”. a new “our”, and they have to move.', 'I\'m an enthusiastic fan of Sara Zarr\'s and couldn\'t wait to read this book from the time I first heard about it. In the interest of full disclosure, I have known Sara since she was a fifth grader, just like Lou. I hope my five star rating encourages you to read this powerful yet sensitive story of a young girl learning about what makes a family.', 'This completed the contemporary book prompt for MG March! Wow. This was such a heartbreakingly beautiful & REAL story. ');
INSERT INTO `goods` VALUES (39, 'Pilar Ramirez and the Escape out of the world 2nd edition', 'picture/2-11.jpg', 'picture/2-11.jpg', 'picture/2-11.jpg', '9.99', 'The Land of Stories meets Dominican myths and legends come to life in Pilar Ramirez \r\nand the Escape from Zafa, a blockbuster contemporary middle-grade fantasy duology starter \r\nfrom Julian Randall. Fans of Tristan Strong and The Storm Runner, here is your next obsession.', 10, 2, 'If you love a terrific main character, TONS of action and adventure, and a bit of history mixed in with modern day, THIS is the book for you!! ', 'This is a Middle Grade. I just could not get into this book. I did not like the writing style of this book, and the characters where just ok. I received an ARC of this book. This review is my own honest opinion about the book like all my reviews are.', 'This book was such a fun read, super recommend.', 'This YA blew my socks off. Randall is a national treasure. Five stars, hands down. ');
INSERT INTO `goods` VALUES (40, 'The Sheep, the Rooster, and the Duck,Tigger,Rabbit, and more', 'picture/2-12.jpg', 'picture/2-12.jpg', 'picture/2-12.jpg', '16.63', 'Wherever there is injustice, nefarious plots, or threats to society, the Sheep, \r\nthe Rooster, and the Duck are there to stop them!', 10, 2, 'Thank you to the Harper Collins and NetGalley for the advanced electronic review copy of this delightful book. This story, reminiscent of the Three Musketeers and also taking place in France, is a wonderful adventure with a promise of more to come. Can’t wait to find out what happens next.', 'I purchased this after reading a review in the New York Times Books (March 17) section and though it sounded interesting. It\'s a sort of wild semi-historical fiction set in France in the 19th century. It has Benjamin Franklin, Marie Antoinette, a team of talking, hot air balloon-flying animals, spies, secret societies, and all manner of crazy things. I could go in to detail, but the Times review will say it better.', 'My eight year old son absolutely loved this book and was enthralled by the beautiful pencil drawings. He\'s a very good reader but he stumbled on some words here and there. I would expect a ten year old would have no issue with it. I also really enjoyed the story which is quite original and a lot of fun.', NULL);
INSERT INTO `goods` VALUES (41, 'Carbonel and Calidor Over 50 Tales and Fables, and well-loved fairy tales. ', 'picture/2-13.jpg', 'picture/2-13.jpg', 'picture/2-13.jpg', '12.99', 'Now in paperback, the third and final entry in Barbara Sleigh\'s enchanting \r\nCarbonel trilogy.', 10, 2, 'I read the 3 Carbonel books when I was a child and was really glad to read it again. Original printings of these books are extremely expensive. Glad to see these out there again.', 'While I read (and fell in love with) the first two Carbonel books as a little girl in the 1960s, I never knew this one existed until 2013. Glad to add it to the collection. I really think these books had a heavy influence on the Harry Potter series, whether this is acknowledged or unacknowledged.', 'Much loved childhood stories. Loved all the Carbonel books. And wanted the originals without updated illustrations. New York Review book editions perfect. Beautifully bound and with original illustrations. No stupid updating.', 'This is a lovely continuance of the chronicles of Carbonel and his humans. Maybe not quite as magical as the first two in the grouping, though. ');
INSERT INTO `goods` VALUES (42, 'Flash Facts,Distilled: Learn the Art of Solving Computational Problems ', 'picture/2-14.jpg', 'picture/2-14.jpg', 'picture/2-14.jpg', '8.29', 'Have you ever wondered: What\'s at the bottom of the sea? Why does polar ice melt? \r\nWhich tools does a forensics team use to solve a crime?', 10, 2, 'I bought this for my 6 year old boy that loves science and superheroes. He doesn\'t like additional reading outside of school, but he gets right into this book once he starts. It is very educational and informative. It is a great read for children interesting in comics, reading, science, etc.', 'This was devoured by an curious eight year old in just hours and now is residing in the bathroom being well used.', 'I thought this would be facts about the flash. My flash obsessed 8 year old hated it.', 'The Flash and other superheroes answer questions about scientific subjects while fighting off supervillains and doing good. They explore atoms, energy, virtual reality technology, DNA, the solar system, and even the depths of the ocean.');
INSERT INTO `goods` VALUES (44, 'The Weather: Pop-up Book,2nd Edition in Silicon Valley Paperback ', 'picture/2-15.jpg', 'picture/2-15.jpg', 'picture/2-15.jpg', '12.70', 'From raucous stormy seas to a welcomingly vivid rainbow, \r\nweather\'s most exciting moments come to brilliant life in this fantastic new pop-up book.', 10, 2, 'The last pop up in the book ripped and broke on first open. I opened it gently, I’m an adult, it was not my fault. I\'m dissatisfied. ', NULL, NULL, NULL);
INSERT INTO `goods` VALUES (45, 'Head First Java: A Brain-Friendly Guide 2nd Edition in Silicon Valley Paperback ', 'picture/3-1.jpg', 'picture/3-1.jpg', 'picture/3-1.jpg', '69.99', 'Learning a complex new language is no easy task especially when it s an object-oriented computer programming language like Java. ', 10, 3, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (46, 'The Pragmatic Programmer: 20th Anniversary Edition,2nd Edition', 'picture/3-2.jpg', 'picture/3-2.jpg', 'picture/3-2.jpg', '27.94', 'The Pragmatic Programmer is one of those rare tech audiobooks you’ll listen, re-listen, and listen to again over the years. \r\nWhether you’re new to the field or an experienced practitioner, you’ll come away with fresh insights each and every time.', 10, 3, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (47, 'Grokking Algorithms: An Illustrated Guide for Programmers', 'picture/3-3.jpg', 'picture/3-3.jpg', 'picture/3-3.jpg', '33.39', 'Grokking Algorithms is a fully illustrated, friendly guide that teaches you how to apply common algorithms to the practical problems you face every day as a programmer.\r\nYou\'ll start with sorting and searching and, as you build up your skills in thinking algorithmically, \r\nyou\'ll tackle more complex concerns such as data compression and artificial intelligence. \r\nEach carefully presented example includes helpful diagrams and fully annotated code samples in Python.', 10, 3, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (48, 'Computer Science Distilled: Learn the Art of Solving Computational Problems ', 'picture/3-4.jpg', 'picture/3-4.jpg', 'picture/3-4.jpg', '25.00', 'A walkthrough of computer science concepts you must know. \r\nDesigned for readers who don\'t care for academic formalities, it\'s a fast and easy computer science guide. ', 10, 3, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (49, 'Start with Why: How Great Leaders Inspire Everyone to Take Action', 'picture/3-5.jpg', 'picture/3-5.jpg', 'picture/3-5.jpg', '12.99', 'The inspirational best seller that ignited a movement and asked us to find our why.\r\n\r\n', 10, 3, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (50, 'Designing Data-Intensive Applications: The Big Ideas Behind Reliable, Scalable', 'picture/3-6.jpg', 'picture/3-6.jpg', 'picture/3-6.jpg', '41.08', 'Data is at the center of many challenges in system design today. Difficult issues need to be figured out, such as scalability, consistency, reliability, efficiency, and maintainability.In addition, we have an overwhelming variety of tools, including relational databases, NoSQL datastores, stream or batch processors, and message brokers.What are the right choices for your application? How do you make sense of all these buzzwords?', 10, 3, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (51, 'Building Microservices: Designing Fine-Grained Systems 2nd Edition ', 'picture/3-7.jpg', 'picture/3-7.jpg', 'picture/3-7.jpg', '40.99', 'As organizations shift from monolithic applications to smaller, self-contained microservices, distributed systems have become more fine-grained.But developing these new systems brings its own host of problems. This expanded second edition takes a holistic view of topics that you need to consider when building, managing, and scaling microservices architectures.\r\n', 10, 3, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (52, 'Chaos Monkeys: Obscene Fortune and Random Failure in Silicon Valley Paperback ', 'picture/3-8.jpg', 'picture/3-8.jpg', 'picture/3-8.jpg', '11.99', 'An irresistible and indispensable 360-degree guide to the new technology establishment.... A must-read.', 10, 3, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (53, 'The 40-Day Social Media Fast:Exchange Your Online Distractions', 'picture/3-9.jpg', 'picture/3-9.jpg', 'picture/3-9.jpg', '10.82', 'In the pattern of her popular 40-Day Sugar Fast, Wendy Speake offers you The 40-Day Social Media Fast. This \"screen sabbatical\" is designed to help you become fully conscious of your dependence on social media so you can purposefully unplug from screens and plug into real life with the help of a very real God.', 10, 3, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (54, 'Quantum Computing: An Applied Approach 1st ed. 2019 Edition ', 'picture/3-10.jpg', 'picture/3-10.jpg', 'picture/3-10.jpg', '39.99', 'This book integrates the foundations of quantum computing with a hands-on coding approach to this emerging field; it is the first work to bring these strands together in an updated manner. This work is suitable for both academic coursework and corporate technical training.', 10, 3, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (55, 'The Founders: The Story of Paypal and the Entrepreneurs ', 'picture/3-11.jpg', 'picture/3-11.jpg', 'picture/3-11.jpg', '14.99', '“A gripping account of PayPal’s origins and a vivid portrait of the geeks and contrarians who made its meteoric rise possible” (Wall Street Journal)—including Elon Musk, Amy Rowe Klement, Peter Thiel, Julie Anderson, Max Levchin, Reid Hoffman,and many others whose stories have never been shared.', 10, 3, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (56, 'Passive Income: Learn How to Make Enough Money to Take an Early Retirement', 'picture/3-12.jpg', 'picture/3-12.jpg', 'picture/3-12.jpg', '12.95', 'If you are wondering how you can earn lots of cash without moving a muscle, you are in the right place! With a little bit of guidance and knowledge, you can be your own boss, earn a great deal of money and take an early retirement.Passive income is the holy grail that everyone is after. Everyone wants to enjoy life to the fullest. This guide will help you turn your dreams into reality.', 10, 3, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (57, 'The Honey Bus: A Memoir of Loss, Courage and a Girl Saved by Bees Kindle', 'picture/4-1.jpg', 'picture/4-1.jpg', 'picture/4-1.jpg', '33.99', 'An extraordinary story of a girl, her grandfather and one of nature’s most mysterious and beguiling creatures: the honeybee. ', 10, 4, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (58, 'The Network State: How To Start a New Country Kindle Edition ', 'picture/4-2.jpg', 'picture/4-2.jpg', 'picture/4-2.jpg', '9.99', '“Balaji has the highest rate of output per minute of good new ideas of anybody I’ve ever met, and The Network State may be his best.” — Marc Andreessen, cofounder of Andreessen Horowitz', 10, 4, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (59, 'Stolen Focus: Why You Can\'t Pay Attention Living and Survival Techniques', 'picture/4-3.jpg', 'picture/4-3.jpg', 'picture/4-3.jpg', '13.99', 'NEW YORK TIMES BESTSELLER • Our ability to pay attention is collapsing. From the New York Times bestselling author of Chasing the Scream and Lost Connections comes a groundbreaking', 10, 4, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (61, 'Bad Blood: Secrets and Lies in a Silicon Valley Startup 2nd edition', 'picture/4-4.jpg', 'picture/4-4.jpg', 'picture/4-4.jpg', '13.99', 'NATIONAL BESTSELLER • The gripping story of Elizabeth Holmes and Theranos—one of the biggest corporate frauds in history—a tale of ambition and hubris set amid the bold promises of Silicon Valley, rigorously reported by the prize-winning journalist. With a new Afterword.', 10, 4, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (68, 'The Prepper\'s Survival Bible: 3 in 1 Collection | Foods to Stockpile, Off-Grid Living', 'picture/4-5.jpg', 'picture/4-5.jpg', 'picture/4-5.jpg', '22.99', 'We live in dangerous times, and wise people worldwide realize that being prepared can mean a difference in the long run. ', 10, 4, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (69, 'Arriving Today: From Factory to Front Door and windows', 'picture/4-6.jpg', 'picture/4-6.jpg', 'picture/4-6.jpg', '21.31', 'The Wall Street Journal technology columnist reveals the fascinating story behind the misleadingly simple phrase shoppers take for granted—“Arriving Today”—in this eye-opening investigation into the new rules of online commerce, transportation, and supply chain management.', 10, 4, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (70, ' Old-Fashioned Toolmaking: The Classic Treatise on Lapping, Threading', 'picture/4-7.jpg', 'picture/4-7.jpg', 'picture/4-7.jpg', '22.01', 'Bringing together the collective wisdom of a past generation of craftsmen, Old Fashioned Toolmaking provides an in-depth record of the skills and techniques that made the mass production revolution of the twentieth century possible. ', 10, 4, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (71, 'Word Search for Kids Ages 6-8: 100 Word Search Puzzles (Search and Find)', 'picture/4-8.jpg', 'picture/4-8.jpg', 'picture/4-8.jpg', '6.99', 'Are you looking for a fun way to boost your child’s learning while providing hours of screen-free entertainment? This book of word search puzzles is the perfect choice. ', 10, 4, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (72, 'DIY SOLAR POWER FOR BEGINNERS: A TECHNICAL GUIDE ON HOW TO DESIGN', 'picture/4-9.jpg', 'picture/4-9.jpg', 'picture/4-9.jpg', '14.99', 'Imagine if you could cut your electricity bill in half by adding a solar setup to your house. Now what if I said you could design and install your DIY solar power system and escape the labor costs?', 10, 4, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (73, 'Haynes Repair Manual,Courage and a Girl Saved by Bees Kindle', 'picture/4-10.jpg', 'picture/4-10.jpg', 'picture/4-10.jpg', '32.27', 'Each Haynes manual is written for the do-it-yourselfer and provides step-by-step instructions based on a complete disassembly of the vehicle.  This hands-on experience provides the reader with specific and detailed', 10, 4, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (74, 'The Complete Driving Education Manual for New Drivers', 'picture/4-11.jpg', 'picture/4-11.jpg', 'picture/4-11.jpg', '9.97', 'If you want to get your loved ones behind the wheel without losing your sleep, then keep reading…', 10, 4, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (75, 'Vanderbilt: The Rise and Fall of an American Dynasty Hardcover ', 'picture/4-12.jpg', 'picture/4-12.jpg', 'picture/4-12.jpg', '14.99', 'New York Times bestselling author and journalist Anderson Cooper teams with New York Times bestselling historian and novelist Katherine Howe to chronicle the rise and fall of a legendary American dynasty—his mother‘s family, the Vanderbilts', 10, 4, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (76, 'Pirate Women: The Princesses, Prostitutes, and Privateers ', 'picture/4-13.jpg', 'picture/4-13.jpg', 'picture/4-13.jpg', '17.99', 'In the first-ever comprehensive survey of the world\'s female buccaneers, Pirate Women: The Princesses, Prostitutes, and Privateers Who Ruled the Seven Seas tells of the women, both real and legendary, who through the ages sailed alongside—and sometimes in command of—their male counterparts.', 10, 4, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (77, 'The First 90 Days: Proven Strategies for Getting Up-4th edition', 'picture/5-1.jpg', 'picture/5-1-1.jpg', 'picture/5-1-2.jpg', '4.73', 'The world\'s most trusted guide for leaders in transition', 10, 5, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (78, 'Profit First: Transform Your Business from a Cash-Eating Monster', 'picture/5-2.jpg', 'picture/5-2.jpg', 'picture/5-2.jpg', '13.42', 'Author of cult classics The Pumpkin Plan and The Toilet Paper Entrepreneur offers a simple, counterintuitive cash management solution that will help small businesses break out of the doom spiral and achieve instant profitability.', 10, 5, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (79, 'Profit First for Real Estate Investing Paperback — 5th edition', 'picture/5-3.jpg', 'picture/5-3-1.jpg', 'picture/5-3-1.jpg', '21.16', 'It\'s time to stop living deal to deal.', 10, 5, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (80, 'The Millionaire Real Estate Investor: Buy Low, Rent High — 5th edition', 'picture/5-4.jpg', 'picture/5-4-1.jpg', 'picture/5-4-2.jpg', '4.40', '\'This book is not just a bargain, it\'s a steal. It\'s filled with practical, workable advice for anyone wanting to build wealth.\'-Mike Summey, co-author of the bestselling The Weekend Millionaire\'s Secrets to Investing in Real Estate', 10, 5, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (81, 'Financial Freedom with Real Estate Investing: The Blueprint To Quitting', 'picture/5-5.jpg', 'picture/5-5-1.jpg', 'picture/5-5-1.jpg', '14.99', 'Discover the (surprising) secret to lifelong financial freedom with real estate investing', 10, 5, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (82, 'Investing in Rental Properties for Beginners: Buy Low, Rent High', 'picture/5-6.jpg', 'picture/5-6-1.jpg', 'picture/5-6-1.jpg', '9.99', 'This will teach you (the ordinary investor) how to tailor your investment strategy to your pocketbooks (and no one else\'s)', 10, 5, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (83, 'Buy It, Rent It, Profit! (Updated Edition): Make Money as a Landlord', 'picture/5-7.jpg', 'picture/5-7-1.jpg', 'picture/5-7-1.jpg', '15.49', 'Now updated for today’s bullish real estate market, this is the go-to, classic entrepreneurial guide for landlords and real estate investors who want to buy and manage rental properties for long-term wealth.', 10, 5, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (84, '$100M Offers: How To Make Offers So Good People Feel Stupid Saying No', 'picture/5-8.jpg', 'picture/5-8-1.jpg', 'picture/5-8-2.jpg', '24.91', 'If you want to get more prospects to reply to your ads for less advertising dollars, and get them to say YES to breathtaking prices...then grab this book, use its contents, and see for yourself.', 10, 5, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (85, 'How To Write Emails That Sell: Secrets From The Most Profitable Emails', 'picture/5-9.jpg', 'picture/5-9-1.jpg', 'picture/5-9-1.jpg', '11.97', 'Short Read To Master The Art Of Emails', 10, 5, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (86, 'Sales Secrets: The World\'s Top Salespeople Share Their Secrets to Success', 'picture/5-10.jpg', 'picture/5-10-1.jpg', 'picture/5-10-2.jpg', '18.98', 'Get Sales Secrets today to learn from the best, study the best, and sell like the best!', 10, 5, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (87, 'Seven Figure Social Selling: Over 400 Pages of Proven Social Selling Scripts', 'picture/5-11.jpg', 'picture/5-11-1.jpg', 'picture/5-11-1.jpg', '18.64', 'Once you\'ve mastered social selling, you\'ll never be without work or money again!', 10, 5, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (88, 'Instagram Income: How Solo Entrepreneurs and Small Companies can Make Money', 'picture/5-12.jpg', 'picture/5-12-1.jpg', 'picture/5-12-1.jpg', '12.99', 'Be ready to never look at IG the same way again.', 10, 5, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (89, 'An Easy & Proven Way to Build Good Habits & Break Bad Ones—2nd edition', 'picture/5-13.jpg', 'picture/5-13-1.jpg', 'picture/5-13-1.jpg', '10.42', 'Tiny Changes, Remarkable Results', 10, 5, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (90, 'The Bond King: How One Man Made a Market, Built an Empire and so on', 'picture/5-14.jpg', 'picture/5-14.jpg', 'picture/5-14.jpg', '20.99', 'From the host of NPR’s Planet Money, the deeply-investigated story of how one visionary, dogged investor changed American finance forever.', 10, 5, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (91, 'Trading in the Zone: Master the Market with Confidence, Discipline', 'picture/5-15.jpg', 'picture/5-15.jpg', 'picture/5-15.jpg', '22.00', 'Douglas uncovers the underlying reasons for lack of consistency and helps traders overcome the ingrained mental habits that cost them money.', 10, 5, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (92, 'Principles for Dealing with the Changing World Order: Why Nations Succeed and Fail ', 'picture/6-1.jpg', 'picture/6-1-1.jpg', 'picture/6-1-1.jpg', '21.00', 'Life and Work, Winner of the Axiom Business Book Award for 2018', 10, 6, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (93, 'The Gates of Europe', 'picture/6-2.jpg', 'picture/6-2-1.jpg', 'picture/6-2-1.jpg', '12.99', 'A New York Times bestseller, this definitive history of Ukraine is “an exemplary account of Europe’s least-known large country', 10, 6, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (94, 'We Don\'t Know Ourselves: A Personal History of Modern Ireland', 'picture/6-3.jpg', 'picture/6-3.jpg', 'picture/6-3.jpg', '25.97', 'A celebrated Irish writer’s magisterial, brilliantly insightful chronicle of the wrenching transformations that dragged his homeland into the modern world.', 10, 6, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (95, 'The Trials of Harry S. Truman: The Extraordinary Presidency of an Ordinary Man, 1945-1953', 'picture/6-4.jpg', 'picture/6-4-1.jpg', 'picture/6-4-1.jpg', '26.79', 'recounting how so ordinary a man met the extraordinary challenge of leading America through the pivotal years of the mid-20th century.', 10, 6, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (96, 'April 1945: The Hinge of History', 'picture/6-5.jpg', 'picture/6-5.jpg', 'picture/6-5.jpg', '24.48', 'Acclaimed historian and New York Times bestselling author Craig Shirley delivers a compelling account of 1945, particularly the watershed events in the month of April, that details how America emerged from World War II as a leading superpower.', 10, 6, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (97, 'Ways and Means: Lincoln and His Cabinet and the Financing of the Civil War', 'picture/6-6.jpg', 'picture/6-6.jpg', 'picture/6-6.jpg', '25.15', 'Captivating . . . [Lowenstein] makes what subsequently occurred at Treasury and on Wall Street during the early 1860s seem as enthralling as what transpired on the battlefield or at the White House.', 10, 6, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (98, 'Lincoln and the Fight for Peace ', 'picture/6-7.jpg', 'picture/6-7-1.jpg', 'picture/6-7-1.jpg', '22.39', 'A groundbreaking, revelatory history of Abraham Lincoln’s plan to secure a just and lasting peace after the Civil War', 10, 6, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (99, 'Salmon P. Chase: Lincoln\'s Vital Rival', 'picture/6-8.jpg', 'picture/6-8-1.jpg', 'picture/6-8-1.jpg', '22.64', 'From an acclaimed, New York Times bestselling biographer, a timely reassessment of Abraham Lincoln’s indispensable Secretary of the Treasury: a leading proponent for black rights both before and during his years in cabinet and later as Chief Justice of the United States.', 10, 6, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (100, 'Campaign of the Century: Kennedy, Nixon, and the Election of 1960', 'picture/6-9.jpg', 'picture/6-9.jpg', 'picture/6-9.jpg', '27.99', '[Gellman] offers as detailed an exploration of the 1960 presidential race as can be found.', 10, 6, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (101, 'The Jazz Age President: Defending Warren G. Harding', 'picture/6-10.jpg', 'picture/6-10.jpg', 'picture/6-10.jpg', '18.97', 'Presidents are ranked wrong. In The Jazz Age President: Defending Warren G. Harding, Ryan Walters mounts a case that Harding deserves to move up—and supplies the evidence to make that case strong', 10, 6, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (102, 'One Damn Thing After Another: Memoirs of an Attorney General', 'picture/6-11.jpg', 'picture/6-11.jpg', 'picture/6-11.jpg', '21.91', 'The former attorney general provides a candid account of his historic tenures serving two vastly different presidents, George H.W. Bush and Donald J. Trump.', 10, 6, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (103, 'How reasonable Americans could support Trump: Helping liberals understand the MAGAverse, and whatever comes next', 'picture/6-12.jpg', 'picture/6-12-1.jpg', 'picture/6-12-1.jpg', '17.00', 'We are a deeply divided country.', 10, 6, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (104, '“Our Crowd”: The Great Jewish Families of New York (Modern Jewish History)', 'picture/6-13.jpg', 'picture/6-13.jpg', 'picture/6-13.jpg', '49.00', 'The #1 New York Times bestseller that traces the rise of the Guggenheims, the Goldmans, and other families from immigrant poverty to social prominence.', 10, 6, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (105, 'Princeton Review AP U.S. History Premium Prep, 2022: 6 Practice Tests + Complete Content Review + Strategies & Techniques (2022)', 'picture/6-14.jpg', 'picture/6-14.jpg', 'picture/6-14.jpg', '17.86', 'Ace the 2022 AP U.S. History Exam with this Premium version of The Princeton Review\'s comprehensive study guide. Includes 6 full-length practice exams, thorough content reviews, targeted test strategies, and access to online extras.', 10, 6, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (106, 'Run, Rose, Run', 'picture/7-1.jpg', 'picture/7-1.jpg', 'picture/7-1.jpg', '18.00', 'a thriller about a young singer-songwriter on the rise and on the run, and determined to do whatever it takes to survive.', 10, 7, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (107, 'Berserk Deluxe Volume 1', 'picture/7-2.jpg', 'picture/7-2-1.jpg', 'picture/7-2-2.jpg', '36.68', 'an international legion of hardcore devotees', 10, 7, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (108, 'The Boy, the Mole, the Fox and the Horse', 'picture/7-3.jpg', 'picture7-3-1.jpg', 'picture/7-3-2.jpg', '5.84', '#1 NEW YORK TIMES BESTSELLER', 10, 7, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (109, 'I\'m Not Scared, You\'re Scared——5th edition', 'picture/7-4.jpg', 'picture/7-4-1.jpg', 'picture/7-4-2.jpg', '14.49', 'The author of Get Out of Your Head offers practical solutions for creating true community, the kind that’s crucial to our mental and spiritual health.', 10, 7, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (110, 'Find Your People: Building Deep Community in a Lonely World', 'picture/7-5.jpg', 'picture/7-5.jpg', 'picture/7-5.jpg', '15.53', 'The author of Get Out of Your Head offers practical solutions for creating true community, the kind that’s crucial to our mental and spiritual health.', 10, 7, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (111, 'Get Out of Your Head: Stopping the Spiral of Toxic Thoughts', 'picture/7-6.jpg', 'picture/7-6-1.jpg', 'picture/7-6-2.jpg', '14.34', 'A must-have resource for anyone looking to get control of their thoughts.', 10, 7, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (112, 'The Butcher and The Wren: A Novel', 'picture/7-7.jpg', 'picture/7-7.jpg', 'picture/7-7.jpg', '27.00', 'From the co-host of chart-topping true crime podcast Morbid, a thrilling debut novel told from the dueling perspectives of a notorious serial killer and the medical examiner following where his trail of victims leads', 10, 7, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (113, 'The Lincoln Highway: A Novel', 'picture/7-8.jpg', 'picture/7-8.jpg', 'picture/7-8.jpg', '14.99', 'A New York Times Notable Book, and Chosen by Oprah Daily, Time, NPR, The Washington Post and Barack Obama as a Best Book of the Year', 10, 7, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (114, 'The Midnight Library: A Novel', 'picture/7-9.jpg', 'picture/7-9.jpg', 'picture7-9.jpg', '13.29', 'Winner of the Goodreads Choice Award for Fiction | A Good Morning America Book Club Pick | Independent (London) Ten Best Books of the Year', 10, 7, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (115, 'The Paris Apartment: A Novel ', 'picture/7-10.jpg', 'picture/7-10.jpg', 'picture/7-10.jpg', '18.16', 'a thriller about a young singer-songwriter on the rise and on the run, and determined to do whatever it takes to survive.', 10, 7, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (116, 'The Maid: A Novel', 'picture/7-11.jpg', 'picture/7-11.jpg', 'picture/7-11.jpg', '17.26', 'The reader comes to understand Molly’s worldview, and to sympathize with her longing to be accepted—a quest that gives The Maid real emotional heft.', 10, 7, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (117, 'Where the Crawdads Sing', 'picture/7-12.jpg', 'picture/7-12.jpg', 'picture/7-12.jpg', '3.95', 'I can\'t even express how much I love this book! I didn\'t want this story to end!', 10, 7, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (118, 'The Lightning Rod: A Zig & Nola Novel', 'picture/7-13.jpg', 'picture/7-13.jpg', 'picture/7-13.jpg', '18.42', 'Zig and Nola are back—in the hugely entertaining, highly anticipated follow-up to Brad Meltzer’s #1 New York Times bestselling thriller The Escape Artist.', 10, 7, NULL, NULL, NULL, NULL);
INSERT INTO `goods` VALUES (119, 'The Club: A Novel', 'picture/7-14.jpg', 'picture/7-14.jpg', 'picture/7-14.jpg', '17.17', 'From the author of People Like Her comes a smart and sinister murder mystery set in the secretive world of exclusive celebrity clubs.', 10, 7, NULL, NULL, NULL, NULL);

-- ----------------------------
-- Table structure for order
-- ----------------------------
DROP TABLE IF EXISTS `order`;
CREATE TABLE `order`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `total` float NULL DEFAULT NULL,
  `amount` int NULL DEFAULT NULL,
  `status` tinyint(1) NULL DEFAULT NULL,
  `paytype` tinyint(1) NULL DEFAULT NULL,
  `name` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `phone` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `address` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `datetime` datetime NULL DEFAULT NULL,
  `user_id` int NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `fk_user_id_idx`(`user_id` ASC) USING BTREE,
  CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 96 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of order
-- ----------------------------
INSERT INTO `order` VALUES (95, 65, 2, 2, 1, 'Hypnus', '1111', '1111', '2022-03-24 15:39:32', 39);

-- ----------------------------
-- Table structure for orderitem
-- ----------------------------
DROP TABLE IF EXISTS `orderitem`;
CREATE TABLE `orderitem`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `price` float NULL DEFAULT NULL,
  `amount` int NULL DEFAULT NULL,
  `goods_id` int NULL DEFAULT NULL,
  `order_id` int NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `fk_order_id_idx`(`order_id` ASC) USING BTREE,
  INDEX `fk_orderitem_goods_id_idx`(`goods_id` ASC) USING BTREE,
  CONSTRAINT `fk_order_id` FOREIGN KEY (`order_id`) REFERENCES `order` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_orderitem_goods_id` FOREIGN KEY (`goods_id`) REFERENCES `goods` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 106 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of orderitem
-- ----------------------------
INSERT INTO `orderitem` VALUES (104, 36, 1, 13, 95);
INSERT INTO `orderitem` VALUES (105, 29, 1, 14, 95);

-- ----------------------------
-- Table structure for recommend
-- ----------------------------
DROP TABLE IF EXISTS `recommend`;
CREATE TABLE `recommend`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `type` tinyint(1) NULL DEFAULT NULL,
  `goods_id` int NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `fk_goods_id_idx`(`goods_id` ASC) USING BTREE,
  CONSTRAINT `fk_goods_id` FOREIGN KEY (`goods_id`) REFERENCES `goods` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 50 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of recommend
-- ----------------------------
INSERT INTO `recommend` VALUES (11, 3, 12);
INSERT INTO `recommend` VALUES (12, 3, 13);
INSERT INTO `recommend` VALUES (13, 3, 14);
INSERT INTO `recommend` VALUES (14, 3, 15);
INSERT INTO `recommend` VALUES (15, 3, 16);
INSERT INTO `recommend` VALUES (17, 3, 18);
INSERT INTO `recommend` VALUES (18, 3, 19);
INSERT INTO `recommend` VALUES (33, 2, 10);
INSERT INTO `recommend` VALUES (34, 2, 11);
INSERT INTO `recommend` VALUES (35, 2, 12);
INSERT INTO `recommend` VALUES (36, 2, 13);
INSERT INTO `recommend` VALUES (37, 2, 14);
INSERT INTO `recommend` VALUES (38, 2, 15);
INSERT INTO `recommend` VALUES (39, 2, 16);
INSERT INTO `recommend` VALUES (40, 2, 18);
INSERT INTO `recommend` VALUES (41, 2, 26);
INSERT INTO `recommend` VALUES (44, 3, 10);
INSERT INTO `recommend` VALUES (47, 2, 9);
INSERT INTO `recommend` VALUES (48, 3, 9);
INSERT INTO `recommend` VALUES (49, 1, 13);

-- ----------------------------
-- Table structure for type
-- ----------------------------
DROP TABLE IF EXISTS `type`;
CREATE TABLE `type`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 11 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of type
-- ----------------------------
INSERT INTO `type` VALUES (1, 'Arts & Photograph');
INSERT INTO `type` VALUES (2, 'Children\'s Book');
INSERT INTO `type` VALUES (3, 'Computing and Technology');
INSERT INTO `type` VALUES (4, 'Engineering and Transportation');
INSERT INTO `type` VALUES (5, 'Business & Money');
INSERT INTO `type` VALUES (6, 'History');
INSERT INTO `type` VALUES (7, 'Literature');

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `email` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `password` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `name` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `phone` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `address` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `isadmin` bit(1) NULL DEFAULT NULL,
  `isvalidate` bit(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `username_UNIQUE`(`username` ASC) USING BTREE,
  UNIQUE INDEX `email_UNIQUE`(`email` ASC) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 40 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of user
-- ----------------------------
INSERT INTO `user` VALUES (1, 'admin', 'admin@vilicode.com', 'admin', 'manager', '3330048', 'The People's Republic of China', b'1', b'0');
INSERT INTO `user` VALUES (37, 'randy', '2396129937@qq.com', 'randy', 'randy', '18819773661', 'Qingyuan Dongcheng', b'0', b'0');
INSERT INTO `user` VALUES (38, 'syz', '3324779867@qq.com', 'pch520', 'syz', '15773852102', 'Changsha, Hunan', b'0', b'0');

SET FOREIGN_KEY_CHECKS = 1;
